<script setup>
import { reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { createCourse } from '../api/courses'
import { moderateReview } from '../api/reviews'

const courseForm = reactive({ name: '', code: '', credits: 15, description: '', workloadHours: 120, prerequisiteIds: [] })
const reviewId = ref(''), reviewLoading = ref(false), courseLoading = ref(false)
async function submitCourse() { if (!courseForm.name || !courseForm.code) return ElMessage.warning('Enter a course name and code.'); courseLoading.value = true; try { await createCourse({ ...courseForm, prerequisiteIds: courseForm.prerequisiteIds.filter(Boolean) }); ElMessage.success('Course created.'); Object.assign(courseForm, { name: '', code: '', credits: 15, description: '', workloadHours: 120, prerequisiteIds: [] }) } catch (err) { ElMessage.error(err.response?.data?.message || 'Unable to create course.') } finally { courseLoading.value = false } }
async function review(status) { if (!reviewId.value) return ElMessage.warning('Enter a review ID.'); reviewLoading.value = true; try { await moderateReview(reviewId.value, status); ElMessage.success(`Review ${status === 'APPROVED' ? 'approved' : 'rejected'}.`); reviewId.value = '' } catch (err) { ElMessage.error(err.response?.data?.message || 'Unable to update review.') } finally { reviewLoading.value = false } }
</script>
<template><section class="admin-page"><div><p class="eyebrow">ADMIN CONSOLE</p><h1>Course and review management</h1><p class="muted">Create courses, assign prerequisites, and moderate submitted reviews.</p></div><div class="admin-grid"><el-card><h2>Create a course</h2><el-form label-position="top"><el-form-item label="Course name"><el-input v-model="courseForm.name" /></el-form-item><el-form-item label="Course code"><el-input v-model="courseForm.code" placeholder="e.g. COMP101" /></el-form-item><div class="form-row"><el-form-item label="Credits"><el-input-number v-model="courseForm.credits" :min="1" /></el-form-item><el-form-item label="Estimated study hours"><el-input-number v-model="courseForm.workloadHours" :min="1" /></el-form-item></div><el-form-item label="Course description"><el-input v-model="courseForm.description" type="textarea" /></el-form-item><el-form-item label="Prerequisite course IDs (comma-separated)"><el-input :model-value="courseForm.prerequisiteIds.join(', ')" placeholder="e.g. 1, 3" @update:model-value="courseForm.prerequisiteIds = $event.split(',').map((id) => Number(id.trim())).filter(Boolean)" /></el-form-item><el-button type="primary" :loading="courseLoading" @click="submitCourse">Create course</el-button></el-form></el-card><el-card><h2>Review moderation</h2><p class="muted">Set a review to APPROVED or REJECTED. Approved reviews appear on the course details page.</p><el-input v-model="reviewId" placeholder="Pending review ID" /><div class="review-actions"><el-button type="success" :loading="reviewLoading" @click="review('APPROVED')">Approve</el-button><el-button type="danger" plain :loading="reviewLoading" @click="review('REJECTED')">Reject</el-button></div><el-alert title="The current master API does not provide a pending-review list. Once you have a review ID, you can moderate it here." type="info" :closable="false" show-icon /></el-card></div></section></template>
<style scoped>.admin-page{max-width:950px;margin:0 auto}.eyebrow{color:var(--accent);font-size:12px;font-weight:700;letter-spacing:.12em}.admin-page h1{margin:6px 0}.muted{color:var(--text);font-size:14px;line-height:1.6}.admin-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:20px;margin-top:28px}.admin-grid h2{margin-top:0}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:14px}.review-actions{display:flex;gap:10px;margin:16px 0}@media(max-width:700px){.admin-grid{grid-template-columns:1fr}}</style>
